# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
# Can be either a string :
requestInfoReplyComment: 

requestInfoUserstoExclude:
  - hiimbex
  - bexo

